/** Punto único de importación de los servicios de Monday: las vistas nunca importan un archivo suelto. */
export * from './usuarios'
export * from './clientes'
export * from './facturas'
/* ===== PAGOS ===== los tres servicios del módulo, todos de LECTURA. */
export * from './proveedores'
export * from './facturasCompra'
export * from './cheques'
export * from './anticiposProveedor'
export * from './retencionGanancias'
export * from './ordenPago'
export * from './anticipos'
export * from './saldos'
export * from './pases'
export * from './cuentas'
export * from './recibos'
export * from './registro'
export * from './envio'
export { mondayHabilitado } from './sdk'
export { BOARDS, COL, ENVIO_RECIBO_INDEX, OP_ENVIO_INDEX } from './columns'
